// Accumulator service for Level 6 Polyglot certification.
//
// Each holon that handles a Relay call increments the counter and appends
// its SDK name to the trace. The final response is mathematically
// verifiable: counter == chain length, trace == exact SDK sequence.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: accum/v1/accum.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RelayRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Running count — each hop increments by 1.
	Counter int32 `protobuf:"varint,1,opt,name=counter,proto3" json:"counter,omitempty"`
	// Ordered list of SDK names that have handled this message.
	Trace []string `protobuf:"bytes,2,rep,name=trace,proto3" json:"trace,omitempty"`
	// Next hop address (method or URI). Empty string = terminal (return result).
	Next          string `protobuf:"bytes,3,opt,name=next,proto3" json:"next,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayRequest) Reset() {
	*x = RelayRequest{}
	mi := &file_accum_v1_accum_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayRequest) ProtoMessage() {}

func (x *RelayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_accum_v1_accum_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayRequest.ProtoReflect.Descriptor instead.
func (*RelayRequest) Descriptor() ([]byte, []int) {
	return file_accum_v1_accum_proto_rawDescGZIP(), []int{0}
}

func (x *RelayRequest) GetCounter() int32 {
	if x != nil {
		return x.Counter
	}
	return 0
}

func (x *RelayRequest) GetTrace() []string {
	if x != nil {
		return x.Trace
	}
	return nil
}

func (x *RelayRequest) GetNext() string {
	if x != nil {
		return x.Next
	}
	return ""
}

type RelayResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Final count after all hops.
	Counter int32 `protobuf:"varint,1,opt,name=counter,proto3" json:"counter,omitempty"`
	// Complete ordered trace of SDK names.
	Trace         []string `protobuf:"bytes,2,rep,name=trace,proto3" json:"trace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayResponse) Reset() {
	*x = RelayResponse{}
	mi := &file_accum_v1_accum_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayResponse) ProtoMessage() {}

func (x *RelayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_accum_v1_accum_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayResponse.ProtoReflect.Descriptor instead.
func (*RelayResponse) Descriptor() ([]byte, []int) {
	return file_accum_v1_accum_proto_rawDescGZIP(), []int{1}
}

func (x *RelayResponse) GetCounter() int32 {
	if x != nil {
		return x.Counter
	}
	return 0
}

func (x *RelayResponse) GetTrace() []string {
	if x != nil {
		return x.Trace
	}
	return nil
}

var File_accum_v1_accum_proto protoreflect.FileDescriptor

const file_accum_v1_accum_proto_rawDesc = "" +
	"\n" +
	"\x14accum/v1/accum.proto\x12\baccum.v1\"R\n" +
	"\fRelayRequest\x12\x18\n" +
	"\acounter\x18\x01 \x01(\x05R\acounter\x12\x14\n" +
	"\x05trace\x18\x02 \x03(\tR\x05trace\x12\x12\n" +
	"\x04next\x18\x03 \x01(\tR\x04next\"?\n" +
	"\rRelayResponse\x12\x18\n" +
	"\acounter\x18\x01 \x01(\x05R\acounter\x12\x14\n" +
	"\x05trace\x18\x02 \x03(\tR\x05trace2A\n" +
	"\x05Accum\x128\n" +
	"\x05Relay\x12\x16.accum.v1.RelayRequest\x1a\x17.accum.v1.RelayResponseB7Z5github.com/organic-programming/go-holons/pkg/accum/v1b\x06proto3"

var (
	file_accum_v1_accum_proto_rawDescOnce sync.Once
	file_accum_v1_accum_proto_rawDescData []byte
)

func file_accum_v1_accum_proto_rawDescGZIP() []byte {
	file_accum_v1_accum_proto_rawDescOnce.Do(func() {
		file_accum_v1_accum_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_accum_v1_accum_proto_rawDesc), len(file_accum_v1_accum_proto_rawDesc)))
	})
	return file_accum_v1_accum_proto_rawDescData
}

var file_accum_v1_accum_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_accum_v1_accum_proto_goTypes = []any{
	(*RelayRequest)(nil),  // 0: accum.v1.RelayRequest
	(*RelayResponse)(nil), // 1: accum.v1.RelayResponse
}
var file_accum_v1_accum_proto_depIdxs = []int32{
	0, // 0: accum.v1.Accum.Relay:input_type -> accum.v1.RelayRequest
	1, // 1: accum.v1.Accum.Relay:output_type -> accum.v1.RelayResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_accum_v1_accum_proto_init() }
func file_accum_v1_accum_proto_init() {
	if File_accum_v1_accum_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_accum_v1_accum_proto_rawDesc), len(file_accum_v1_accum_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_accum_v1_accum_proto_goTypes,
		DependencyIndexes: file_accum_v1_accum_proto_depIdxs,
		MessageInfos:      file_accum_v1_accum_proto_msgTypes,
	}.Build()
	File_accum_v1_accum_proto = out.File
	file_accum_v1_accum_proto_goTypes = nil
	file_accum_v1_accum_proto_depIdxs = nil
}
