// Accumulator service for Level 6 Polyglot certification.
//
// Each holon that handles a Relay call increments the counter and appends
// its SDK name to the trace. The final response is mathematically
// verifiable: counter == chain length, trace == exact SDK sequence.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: accum/v1/accum.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Accum_Relay_FullMethodName = "/accum.v1.Accum/Relay"
)

// AccumClient is the client API for Accum service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AccumClient interface {
	// Relay increments the counter, appends this SDK's name to the trace,
	// and either forwards to the next hop or returns the accumulated result.
	Relay(ctx context.Context, in *RelayRequest, opts ...grpc.CallOption) (*RelayResponse, error)
}

type accumClient struct {
	cc grpc.ClientConnInterface
}

func NewAccumClient(cc grpc.ClientConnInterface) AccumClient {
	return &accumClient{cc}
}

func (c *accumClient) Relay(ctx context.Context, in *RelayRequest, opts ...grpc.CallOption) (*RelayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RelayResponse)
	err := c.cc.Invoke(ctx, Accum_Relay_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccumServer is the server API for Accum service.
// All implementations must embed UnimplementedAccumServer
// for forward compatibility.
type AccumServer interface {
	// Relay increments the counter, appends this SDK's name to the trace,
	// and either forwards to the next hop or returns the accumulated result.
	Relay(context.Context, *RelayRequest) (*RelayResponse, error)
	mustEmbedUnimplementedAccumServer()
}

// UnimplementedAccumServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAccumServer struct{}

func (UnimplementedAccumServer) Relay(context.Context, *RelayRequest) (*RelayResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Relay not implemented")
}
func (UnimplementedAccumServer) mustEmbedUnimplementedAccumServer() {}
func (UnimplementedAccumServer) testEmbeddedByValue()               {}

// UnsafeAccumServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AccumServer will
// result in compilation errors.
type UnsafeAccumServer interface {
	mustEmbedUnimplementedAccumServer()
}

func RegisterAccumServer(s grpc.ServiceRegistrar, srv AccumServer) {
	// If the following call panics, it indicates UnimplementedAccumServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Accum_ServiceDesc, srv)
}

func _Accum_Relay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RelayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccumServer).Relay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Accum_Relay_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccumServer).Relay(ctx, req.(*RelayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Accum_ServiceDesc is the grpc.ServiceDesc for Accum service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Accum_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "accum.v1.Accum",
	HandlerType: (*AccumServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Relay",
			Handler:    _Accum_Relay_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "accum/v1/accum.proto",
}
